use type name in Display impl for errors with no other message set
Otherwise, with nested errors, you can end up with unhelpful errors like
this (example printed by `anyhow`):

```
Error: failed to get metadata for "/temp/spoopadoop"

Caused by:
    0: Dropbox API endpoint returned an error: There is nothing at the given path.
    1: There is nothing at the given path.
    2: There is nothing at the given path.
```

instead, with this change, you get:
```
Error: failed to get metadata for "/temp/spoopadoop"

Caused by:
    0: Dropbox API endpoint returned an error: GetMetadataError: There is nothing at the given path.
    1: GetMetadataError: There is nothing at the given path.
    2: There is nothing at the given path.
```
which is less repetitive and gives a better indication of what actually went wrong.